### ISSUE TITLE
support select/deselect in table header

### ISSUE THREAD

**Issue by luqin** [DataTables/Select#14]

**Comment by DataTables** [comment]
Selection of the columns? That can be done via the API at the moment and simply binding a click handler. I don't currently intend to offer an option built into Select that provides this ability, but a column widget extension for DataTables that I've been thinking about would provide this ability.

As this isn't something I plan to offer in Select at the moment, and because it is possible I'm going to close this issue for now, but feel free to continue the discussion if you would like.
