### ISSUE TITLE
Clicking on a row doesn't seem to always trigger a select

### ISSUE THREAD

**Issue by dbalders** [DataTables/Select#18]
When you click on a row, the first time it selects, but sometimes if you then unselect and then try to select again, It will not select. It seems inconsistent when it will select again and when it wont. Sometimes it just highlights the text instead of selecting the row (prob capturing the double click on a text field). 

Code Example: http://live.datatables.net/juxavonu/2/

![buttons select](https://cloud.githubusercontent.com/assets/4715098/14252742/812f89ce-fa3d-11e5-80b4-327b42d9f49d.gif)

OS: Mac OS X 10.11
Browser: Chrome 49.0.2623.87

**Comment by DataTables** [comment]
If text is selected in the table then the row won't be selected (the assumption being that the user wanted to select text rather than select the row). Depending on how and where you click, this could trigger text selection and thus not select the row (as shown towards the end of the above loop).

I found it really annoying that a row was highlighted when I was just trying to select text which is why that is in there.Possibly it should be a configurable option, but I currently think it should stay as it is unless there is a good reason to change it?

**Comment by dbalders** [comment]
That makes sense. Now that you said that, this is probably more of a problem as I go through testing than it would be with people actually using it. Makes sense to let them select text if they would like rather than having the functionality of being able to click on and off rapidly.
