### ISSUE TITLE
Append info to multiple instances of the table info

### ISSUE THREAD

**Issue by wadtech** [DataTables/Select#20]
I've got a table where the pagination and information is included multiple times in the DOM string. Select doesn't appear to be adding its own info string to both elements.

Is there an option to do this?

![image](https://cloud.githubusercontent.com/assets/1141692/15431991/4186bd20-1ea4-11e6-8bff-df03ff59df8c.png)

**Comment by DataTables** [comment]
No that looks to be a bug. Thanks for letting me know about it.

**Comment by wadtech** [comment]
No problem, thanks for the quick response :smile:

**Comment by plsgard** [comment]
I have the same problem, I think I know why. In fact, in the **info** method (line 444), you use the jQuery **.append()** function (line 475) to add the option output inside each info instance.
But, according to the jQuery Documentation, it seems that ".append()" moves the element in the DOM :
> As shown in the discussion for .append(), normally when an element is inserted somewhere in the DOM, it is moved from its old location.

So, when the code tries to set the output in a new info instance, the output elements are moved from the previous info to the new one.
I think, you should use .clone() on output in order to get a copy for each info instance.
Replace :
`if ( output.text() !== '' ) {
			el.append( output );
		}`
by
`if ( output.text() !== '' ) {
			el.append( output.clone() );
		}`
I gonna try to make a PR for this.

**Comment by DataTables** [comment]
Thanks very much for the PR @plsgard! The clone solution is a nice way of resolving it - and your debugging it very insightful!

However, I'm not going to pull the PR in as I believe that more fundamentally the code structure there is just plain broken. With the clone there will always be at least one more element created than is actually needed. Its not going to effect performance in reality but, it feels cleared to avoid it, so I've committed 489e376 which restructures that method to be a little more approriate for the loop.

**Comment by plsgard** [comment]
No problem, I suspected that. I provided the fastest (not the better) way. This is why the PR process is good.
Thanks !

**Comment by wadtech** [comment]
Thank you for your work both, I appreciate it
