### ISSUE TITLE
Custom function for calculating the number of selected items

### ISSUE THREAD

**Issue by Stadly** [DataTables/Select#21]
It would be great if how to calculate the number of selected rows/columns/cell could be specified. For example, when implementing a solution that retains selected rows when using server-side processing, a custom function for calculating the number of selected rows is needed. In this case, `api.rows( { selected: true } ).flatten().length` will only show the number of selected rows on the current page with the current filtering. I'm imagining a solution where the method used for calculating the number of selected items chould be specified when initializing `DataTables/Select`. For example like this:

```
$('#table').DataTable({
    select: {
        calculateSelectedRows: function() { return selectedRows.length; }
    }
});
```

**Comment by DataTables** [comment]
Interesting. The problem with this is that the rows on the other pages aren't really selected. You would need to retain some kind of custom store for them. For example, with Editor you couldn't edit them since their data isn't at the client-side, so it would be misleading to have them "shown" as selected.

Perhaps there needs to be an API to allow continuous selection like this. Its not something I was planning, but I can see it might be useful.

**Comment by AllanJard** [comment]
There needs to be some kind of way to integrate with server-side processing, which #46 covers. Going to close in favour of that one. There are no plans at this time for that integration though.
