### ISSUE TITLE
Could you provide the css file?

### ISSUE THREAD

**Issue by kennynaoh** [DataTables/Select#26]
Hello @DataTables ,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
Whether you could provide the css file on [npm](https://www.npmjs.com/package/datatables.net-select) or not?
Thanks for your help!

https://github.com/cdnjs/cdnjs/issues/8515
https://github.com/cdnjs/cdnjs/pull/8530

**Comment by DataTables** [comment]
Hi,

Because DataTables and its extensions support multiple styling frameworks, there are multiple distribution packages for DataTables core and its extensions. For example, for _Select_ there is the core JS repo, and then you can select one of Bootstrap, DataTables styling, Foundation, etc.

Since there isn't really a way to specify options for npm package as to which style you want to include I had to break it into multiple repos. As such this repo is just a source repo - the distribution repos are:
- [DataTables/Dist-DataTables-Select](https://github.com/DataTables/Dist-DataTables-Select)
- [DataTables/Dist-DataTables-Select-Bootstrap](https://github.com/DataTables/Dist-DataTables-Select-DataTables)
- [DataTables/Dist-DataTables-Select-Bootstrap](https://github.com/DataTables/Dist-DataTables-Select-DataTables)
- [DataTables/Dist-DataTables-Select-Foundation](https://github.com/DataTables/Dist-DataTables-Select-Foundation)
- [DataTables/Dist-DataTables-Select-jQueryUI](https://github.com/DataTables/Dist-DataTables-Select-jQueryUI)

With more planned for the future (SemanticUI for example).

[npm installation documentation](https://datatables.net/download/npm) is available on the DataTables site.

**Comment by kennynaoh** [comment]
Hello, sorry for late response.
I found that there is a file `select.dataTables.scss` on git repo, but not built.
Could you build it to css file on git repo and we can automatically grab when you publish the new release?
Or, I found that there are `select.dataTables.css` on git repo you offer above, https://github.com/DataTables/Dist-DataTables-Select-DataTables, I can handle this, too.
What do you think?
Thanks!

**Comment by DataTables** [comment]
That is correct - use the distribution repo for the compiled files. This is a source repo.

**Comment by kennynaoh** [comment]
What about the old version `v1.0.0`?
I can't find that `v1.0.0` on https://github.com/DataTables/Dist-DataTables-Select-DataTables, but there is exist on this repo.
Or you don't care?
Please help me confirm that.
Thanks!

**Comment by DataTables** [comment]
The distribution repos were created after 1.0.0 was released. If you really need the old version [it is available here](http://cdn.datatables.net/select/1.0.0/).

**Comment by kennynaoh** [comment]
Thank you so much!

**Comment by kennynaoh** [comment]
Is there any reference to know the css file is come from this repo https://github.com/DataTables/Dist-DataTables-Select-DataTables?
Thanks!

**Comment by DataTables** [comment]
Not directly. The `datatables.net-dt` package on NPM is sourced from that repo.

**Comment by kennynaoh** [comment]
Hello, I have other question want to ask. I grab the `js` file from https://github.com/DataTables/Select and the `css` file from https://github.com/DataTables/Dist-DataTables-Select-DataTables. Could these two main files combine together in a single repository or package in the future? The auto-update config can't update from two sources. Thanks!

cc https://github.com/cdnjs/cdnjs/pull/8530

**Comment by DataTables** [comment]
Get the JS from https://github.com/DataTables/Dist-DataTables-Select.

The reason there are multiple build repos are because DataTables supports multiple styling frameworks. I wasn't able to find a nice clean way to have multiple styling files (including the relevant Javascript for each) in a single repo in a way that made it easy to use with npm.

As I mentioned above, this is a src repo and shouldn't be used for distribution. The distribution repos are there for that.

**Comment by AllanJard** [comment]
Closing as the distribution repos include the CSS files.
