### ISSUE TITLE
Select rows lost on ajax paging with serverSide

### ISSUE THREAD

**Issue by d3v2a** [DataTables/Select#35]
When i select items and change page on table, selected element was lost. 
If i only change length there is no problem.

```js
$('#table').dataTable({
  select: true,
  columns: [....],
  serverSide: true,
  rowId: 'id',
});
```  

- DataTables 1.10.19
- Select for DataTables 1.2.7

**Comment by DataTables** [comment]
Yes, this is a limitation when using server-side processing. Because the row selection is client-side and the data is server-side, there is a disconnect. As such, rows cannot be selected when they are not displayed.

That is not the case if you use client-side processing, where all rows are available at the client-side.

**Comment by d3v2a** [comment]
i solved the problem by storing selected ids and then reselect that ids on table draw event

it's not possible to store ids in the plugin ?

**Comment by DataTables** [comment]
Yes - that is a possibility. The reason I haven't implement that is that it gives the impression that rows on different pages continue to be selected when they can't be. For example select a row on one page, change page and click a 'delete' action. The row can't be deleted because it no longer exists on the client-side.

It would be possible to send your list of ids to the server and have it delete them, but that is implementation specific.
