### ISSUE TITLE
Installation of select plugin < 2.0 installs datatables.net 2.0.0

### ISSUE THREAD

**Issue by codegain** [DataTables/Select#50]
Hi,

I recently updated my dependencies and noticed that the version constraint used in datatables.net-select-dt >1.3.4 (f.e. see https://github.com/DataTables/Dist-DataTables-Select-DataTables/blob/master/package.json) causes the plugin to install datatables 2.0.0 and breaking my existing application.

1.3.3 is the last version which has a fixed dependency of `datatables.net-select: 1.3.3`, everything afterwards has `>=1.3.3` which in turn installs the latest version of `datatables.net-select` which installs the 2.0.0 datatables.

I currently worked around this by using

```
    "overrides": {
        "datatables.net@>2": "1.13.8"
    },
```

in my package.json, but I think this should be fixed.

**Comment by AllanJard** [comment]
Apologies for the error! I've just tagged up Select 1.7.1 for npm, which uses `"datatables.net": "^1.13.0"` for its dependencies. Select 2.0.0 is still the `latest` tag in npm, but hopefully this should help ease the problems a little bit. It might not be a full solution since some of the older packages had dodgy dependency values as you note - fro such cases an override would be needed.

My Buttons and Responsive extensions have a similar issue for their last major releases and I'll do the same with them.

**Comment by codegain** [comment]
@AllanJard Seems to work, thank you!
