### ISSUE TITLE
Cannot find name 'ObjectColumnRender'.ts(2304)

### ISSUE THREAD

**Issue by alpozgur** [DataTables/Select#56]
Hi;
I'm using datatables.net 2.1.7 and updated the select to 2.1.0 today... in types.d.ts getting error of Cannot find name 'ObjectColumnRender'.ts(2304) at 
	interface DataTablesStaticRender {
		/**
		 * Display a checkbox in the column's cells to be used for and represent
		 * row selection.
		 */
		select(): ObjectColumnRender;

		/**
		 * Display a checkbox in the column's cells to be used for and represent
		 * row selection, with the `value` and `name` attributes for the checkbox
		 * `input` being set by properties from the row's data object.
		 *
		 * @param valueProp Name of the data property where the `value` for the
		 *   checkbox is.
		 * @param nameProp Name of the data property where the `name` for the
		 *   checkbox is.
		 */
		select(valueProp: string, nameProp: string): ObjectColumnRender;
	}

**Comment by AllanJard** [comment]
Thank you. The issue was that I wasn't exporting that particular property from the DataTables types. I've [committed a fix for that](https://github.com/DataTables/DataTablesSrc/commit/0b07375e57ac56dd2ce582641115169eccd6340d) and it will be in the next patch release of DataTables, which I expect to be towards the end of next week.
